# Generated by Django 4.1.3 on 2023-02-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_options_product_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_white_date_color',
            field=models.BooleanField(default=False),
        ),
    ]
