# Generated by Django 4.1.3 on 2023-02-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_pin_heart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rank_score',
            field=models.FloatField(default=0),
        ),
    ]
