# Generated by Django 4.1.3 on 2023-03-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_rank_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frontend_static_page_generate',
            field=models.BooleanField(default=False),
        ),
    ]
