# Generated by Django 4.1.3 on 2023-03-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_frontend_static_page_generate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
