# Generated by Django 4.1.3 on 2023-06-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='frontend_static_page_generate',
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_affliate_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
