# Generated by Django 4.1.3 on 2023-01-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catch_phrase', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='images/home/')),
            ],
        ),
    ]
