# Generated by Django 4.1.3 on 2023-03-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userprofile_articles_viewed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
            ],
        ),
    ]
