# Generated by Django 4.1.3 on 2023-06-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userprofile_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffliatePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Amazon', max_length=255)),
                ('icon_str', models.CharField(default='fa fa-amzon', max_length=255)),
                ('logo', models.ImageField(upload_to='affliate_partner_logos/')),
                ('desc', models.TextField()),
            ],
        ),
    ]
