# Generated by Django 4.1.3 on 2023-06-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_affliatepartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affliatepartner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='affliate_partner_logos/'),
        ),
    ]
