# Generated by Django 4.1.3 on 2023-06-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_affliatepartner_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affliatepartner',
            name='icon_str',
        ),
    ]
